### ISSUE TITLE
hello, I got a ValuError

### ISSUE THREAD

**Issue by pak24** [cosimoiaia/KERAS-Show-and-Tell#2]
I run the Show-and-Tell.py file and I get a ValueError:Operands could not be broadcast together with shapes (300,) (256,)
the ValueError is occur in the line 227

(here my idea: I presume line 225 and line 220 is inconsistent, 
I thought perhaps change line 225 to lang_model_s = LSTM(300)(lang_model_d)  
or 
change the constant in line 220 to  256 )

I really look forword to you answer.

**Comment by cosimoiaia** [comment]
Hi, 
The mistake is actually on the **Dense** layer which takes incorrectly EMBEDDING_DIM and should be 256, that's why when you try to add them together you get the incorrect shape exception.
I corrected it on the .py file but you can also check the notebook .ipynb in the repo which is correct and it was the one I used in colab for dev/testing.

Cheers.
